//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebParts.WebParts.UpdateEmployee {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class UpdateEmployee {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtBirthdate;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList rbGender;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtSalary;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList chDepartment;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtProfileURL;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtProfileURLDes;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtBriefofExp;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "16.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(UpdateEmployee target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtName";
            @__ctrl.MaxLength = 100;
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtBirthdate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtBirthdate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtBirthdate";
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Date;
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlrbGender() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.rbGender = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "rbGender";
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSalary() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtSalary = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Number;
            @__ctrl.ID = "txtSalary";
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlchDepartment() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.chDepartment = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "chDepartment";
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtProfileURL() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtProfileURL = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtProfileURL";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtProfileURLDes() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtProfileURLDes = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.MultiLine;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Description");
            @__ctrl.ID = "txtProfileURLDes";
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtBriefofExp() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtBriefofExp = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.MultiLine;
            @__ctrl.ID = "txtBriefofExp";
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSave";
            @__ctrl.CssClass = "btn btn-button";
            @__ctrl.EnableViewState = false;
            @__ctrl.Text = "Update";
            @__ctrl.OnClientClick = "checkPermission(); return false;";
            @__ctrl.Click -= new System.EventHandler(this.btnSave_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void @__BuildControlTree(global::EmployeeWebParts.WebParts.UpdateEmployee.UpdateEmployee @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<link type=""text/css"" rel=""stylesheet"" href=""/Style%20Library/CSS/bootstrap.min.css"" />
<script src=""/Style Library/Scripts/jquery-3.5.1.min.js""></script>

<div class=""container"">

    <div class=""row"">
        <div class=""col-md-3 col-sm-3"">
            <label for=""txtName"" id=""lblName"">Name</label>
        </div>
        <div class=""col-md-6 col-sm-6"">
            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtName();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n        </div>\r\n    </div>\r\n    <div class=\"row\">\r\n        <div class=\"col-md" +
                        "-3 col-sm-3\">\r\n            <label for=\"txtBirthdate\" id=\"lblBirthdate\">Birthdate" +
                        "</label>\r\n        </div>\r\n        <div class=\"col-md-6 col-sm-6\">\r\n            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            @__ctrl2 = this.@__BuildControltxtBirthdate();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"row\">\r\n        <div class=\"co" +
                        "l-md-3 col-sm-3\">\r\n            <label for=\"rbGender\" id=\"lblGender\">Gender</labe" +
                        "l>\r\n        </div>\r\n        <div class=\"col-md-6 col-sm-6\">\r\n            "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl3;
            @__ctrl3 = this.@__BuildControlrbGender();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"row\">\r\n        <div class=\"col-" +
                        "md-3 col-sm-3\">\r\n            <label for=\"txtSalary\" id=\"lblSalary\">Salary</label" +
                        ">\r\n        </div>\r\n        <div class=\"col-md-6 col-sm-6\">\r\n            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControltxtSalary();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"row\">\r\n        <div class=\"co" +
                        "l-md-3 col-sm-3\">\r\n            <label for=\"chDepartment\" id=\"lblDepartment\">Depa" +
                        "rtment</label>\r\n        </div>\r\n        <div class=\"col-md-6 col-sm-6\">\r\n       " +
                        "     "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl5;
            @__ctrl5 = this.@__BuildControlchDepartment();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"row\">\r\n        <div class=\"col-" +
                        "md-3 col-sm-3\">\r\n            <label for=\"txtProfileURL \" id=\"lblProfileURL\">Prof" +
                        "ile URL</label>\r\n        </div>\r\n        <div class=\"col-md-4 col-sm-4\">\r\n      " +
                        "      "));
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControltxtProfileURL();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n        <div class=\"col-md-3 col-sm-3\">\r\n            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl7;
            @__ctrl7 = this.@__BuildControltxtProfileURLDes();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
        </div>
    </div>

    <div class=""row"">
        <div class=""col-md-3 col-sm-3"">
            <label for=""txtBriefofExp "" id=""lbltxtBriefofExp"">Brief of experience</label>
        </div>
        <div class=""col-md-6 col-sm-6"">
            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            @__ctrl8 = this.@__BuildControltxtBriefofExp();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"row\">\r\n\r\n        <div class=\"co" +
                        "l-md-6 col-sm-6\" style=\"align-content: center\">\r\n            "));
            global::System.Web.UI.WebControls.Button @__ctrl9;
            @__ctrl9 = this.@__BuildControlbtnSave();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n    </div>\r\n    <label id=\"lblErrorMessage\"></label>\r\n</div>\r\n\r" +
                        "\n\r\n<script type=\"text/javascript\">\r\n    \'use strict\'\r\n    $(document).ready(func" +
                        "tion () {\r\n        $.ajax({\r\n            url: _spPageContextInfo.webAbsoluteUrl " +
                        "+ \"/_api/web/lists/GetByTitle(\'Employees\')/fields?$filter=EntityPropertyName eq " +
                        "\'EmployeeDepartment\'\",\r\n            type: \"GET\",\r\n            headers: {\r\n      " +
                        "          \"accept\": \"application/json;odata=verbose\",\r\n            },\r\n         " +
                        "   success: function (data) {\r\n                console.log(data.d.results[0].Cho" +
                        "ices.results);\r\n                var depChoices = data.d.results[0].Choices.resul" +
                        "ts;\r\n                for (var dep of depChoices) {\r\n                    console." +
                        "log(dep);\r\n                    $(\"select[id*=\'chDepartment\']\").append(`<option V" +
                        "alue=\"${dep}\">${dep}</option>`);\r\n                }\r\n            },\r\n           " +
                        " error: function (error) {\r\n                alert(JSON.stringify(error));\r\n     " +
                        "       }\r\n        });\r\n\r\n        $.ajax({\r\n            url: _spPageContextInfo.w" +
                        "ebAbsoluteUrl + \"/_api/web/lists/GetByTitle(\'Employees\')/fields?$filter=EntityPr" +
                        "opertyName eq \'EmployeeGender\'\",\r\n            type: \"GET\",\r\n            headers:" +
                        " {\r\n                \"accept\": \"application/json;odata=verbose\",\r\n            },\r" +
                        "\n            success: function (data) {\r\n                console.log(data.d.resu" +
                        "lts[0].Choices.results);\r\n                var genderChoices = data.d.results[0]." +
                        "Choices.results;\r\n                for (var gender of genderChoices) {\r\n         " +
                        "           console.log(gender);\r\n                    $(\"select[id*=\'rbGender\']\")" +
                        ".append(`<option Value=\"${gender}\">${gender}</option>`);\r\n                }\r\n   " +
                        "         },\r\n            error: function (error) {\r\n                alert(JSON.s" +
                        "tringify(error));\r\n            }\r\n        });\r\n    });\r\n\r\n\r\n\r\n    var empId = \"\"" +
                        ";\r\n    var listTitle = \"Employees\";\r\n    var allowAdd = false;\r\n    $(document)." +
                        "ready(function () {\r\n        //get employee id from Url \r\n        empId = GetUrl" +
                        "KeyValue(\'empId\');\r\n        getItem();\r\n    });\r\n\r\n\r\n    // Get Item and Calling" +
                        " Update Fields\r\n    function getItem() {\r\n        $.ajax({\r\n            url: _sp" +
                        "PageContextInfo.webAbsoluteUrl + \"/_api/web/lists/getbytitle(\'\" + listTitle + \"\'" +
                        ")/items(\" + empId + \")\",\r\n            method: \"GET\",\r\n            headers: { \"Ac" +
                        "cept\": \"application/json; odata=verbose\" },\r\n            success: function (data" +
                        ") {\r\n                updateFields(data.d);\r\n            },\r\n            error: f" +
                        "unction (error) {\r\n                console.log(error);\r\n            }\r\n        }" +
                        ");\r\n\r\n    }\r\n\r\n\r\n    // update fields\r\n    function updateFields(employee) {\r\n  " +
                        "      $(\"input[id*=\'txtName\']\").val(employee[\'EmployeeName\']);\r\n        $(\"input" +
                        "[id *= \'txtBirthdate\']\").val(new Date(employee[\'EmployeeBirthdate\']).format(\'yyy" +
                        "y-MM-dd\'));\r\n        $(\"textarea[id *= \'txtBriefofExp\']\").val(employee[\'BriefOfE" +
                        "xperience\']);\r\n        $(\"select[id*=\'rbGender\']\").val(employee[\'EmployeeGender\'" +
                        "]);\r\n        $(\"input[id *= \'txtSalary\']\").val(employee[\'EmployeeSalary\']);\r\n   " +
                        "     $(\"select[id*=\'chDepartment\']\").val(employee[\'EmployeeDepartment\']);\r\n     " +
                        "   $(\"input[id*=\'txtProfileURL\']\").val(employee[\'ProfileURL\'].Url);\r\n        $(\"" +
                        "textarea[id*=\'txtProfileURLDes\']\").val(employee[\'ProfileURL\'].Description);\r\n   " +
                        " }\r\n\r\n\r\n\r\n\r\n    //Update listItem in list \r\n    function UpdateListItemUsingItem" +
                        "Id(Id) {\r\n\r\n        //fill Item With New Data \r\n        var item = {\r\n          " +
                        "  \"__metadata\": {\r\n                \"type\": \"SP.Data.EmployeeListItem\"\r\n         " +
                        "   },\r\n            \"Title\": $(\"input[id*=\'txtName\']\").val(),\r\n            \"Emplo" +
                        "yeeName\": $(\"input[id *= \'txtName\']\").val(),\r\n            \"EmployeeBirthdate\": $" +
                        "(\"input[id *= \'txtBirthdate\']\").val(),\r\n            \"BriefOfExperience\": $(\"text" +
                        "area[id *= \'txtBriefofExp\']\").val(),\r\n            \"EmployeeGender\": $(\"select[id" +
                        "*=\'rbGender\'] :selected\").val(),\r\n            \"EmployeeSalary\": parseInt($(\"inpu" +
                        "t[id *= \'txtSalary\']\").val()),\r\n            \"EmployeeDepartment\": $(\"select[id*=" +
                        "\'chDepartment\'] :selected\").val(),\r\n            \"ProfileURL\": {\r\n               " +
                        " \'__metadata\': { \'type\': \'SP.FieldUrlValue\' },\r\n                \'Description\': $" +
                        "(\"textarea[id *= \'txtProfileURLDes\']\").val(),\r\n                \'Url\': $(\"input[i" +
                        "d *= \'txtProfileURL\']\").val()\r\n            }\r\n        };\r\n\r\n        var apiURl =" +
                        " _spPageContextInfo.webAbsoluteUrl + \"/_api/web/lists/GetByTitle(\'\" + listTitle " +
                        "+ \"\')/items(\" + Id + \")\";\r\n        $.ajax\r\n            ({\r\n                url: " +
                        "apiURl,\r\n                type: \"POST\",\r\n                headers:\r\n              " +
                        "  {\r\n                    \"Accept\": \"application/json;odata=verbose\",\r\n          " +
                        "          \"Content-Type\": \"application/json;odata=verbose\",\r\n                   " +
                        " \"IF-MATCH\": \"*\",\r\n                    \"X-HTTP-Method\": \"MERGE\",\r\n              " +
                        "      \"X-RequestDigest\": $(\"#__REQUESTDIGEST\").val()\r\n                },\r\n      " +
                        "          data: JSON.stringify(item),\r\n                success: function (data, " +
                        "status, xhr) {\r\n                    //console.log(data.d.results);\r\n            " +
                        "        var r = confirm(\"Successful Message!\");\r\n                    if (r == tr" +
                        "ue) {\r\n                        window.location.href = \"/SitePages/Employees.aspx" +
                        "\";\r\n                    }\r\n                },\r\n                error: function (" +
                        "xhr, status, error) {\r\n                    console.log(\"Failed\");\r\n             " +
                        "   }\r\n            });\r\n    }\r\n\r\n\r\n    // check permoissions forUser before Updat" +
                        "e \r\n    function getListUserEffectivePermissions() {\r\n        var endpointUrl = " +
                        "_spPageContextInfo.webAbsoluteUrl + \"/_api/web/lists/getbytitle(\'\" + listTitle +" +
                        " \"\')/items(\" + empId + \")/getusereffectivepermissions(@u)?@u=\'\" + encodeURICompo" +
                        "nent(_spPageContextInfo.userLoginName) + \"\'\";\r\n        return $.getJSON(endpoint" +
                        "Url);\r\n    }\r\n\r\n    function parseBasePermissions(value) {\r\n        var permissi" +
                        "ons = new SP.BasePermissions();\r\n        permissions.initPropertiesFromJson(valu" +
                        "e);\r\n        allowAdd = permissions.has(SP.PermissionKind.addListItems);\r\n      " +
                        "  if (allowAdd)\r\n            UpdateListItemUsingItemId(empId);\r\n        console." +
                        "log(allowAdd);\r\n    }\r\n\r\n\r\n    function checkPermission() {\r\n        var valid =" +
                        " false;\r\n        var txtError = $(\"#lblErrorMessage\");\r\n        txtError.val(\"\")" +
                        ";\r\n        var textName = $(\"input[id*=\'txtName\']\").val();\r\n        var birthDat" +
                        "e = $(\"input[id *= \'txtBirthdate\']\").val();\r\n        var txtSalary = $(\"input[id" +
                        " *= \'txtSalary\']\").val();\r\n        var txtBriefofExp = $(\"textarea[id *= \'txtBri" +
                        "efofExp\']\").val();\r\n        var emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\" +
                        ".[a-zA-Z]{2,4}$/;\r\n        if (textName.length < 20 || textName.length > 100) {\r" +
                        "\n            txtError.append(\"Name Length between 20 & 100 \").show();\r\n         " +
                        "   valid = false;\r\n        }\r\n        if (new Date(birthDate) > new Date() || bi" +
                        "rthDate === \"\") {\r\n            txtError.append(\" Date is inValid\");\r\n           " +
                        " valid = false;\r\n        }\r\n        if (txtSalary === null || txtSalary === unde" +
                        "fined) {\r\n            txtError.append(\" Salary required\");\r\n            valid = " +
                        "false;\r\n        }\r\n        if (txtBriefofExp === null || txtBriefofExp === undef" +
                        "ined || txtBriefofExp.length > 200) {\r\n            txtError.append(\" Brief  requ" +
                        "ired\");\r\n            valid = false;\r\n        }\r\n        if (!valid) {\r\n         " +
                        "   txtError.show();\r\n        }\r\n        debugger;\r\n        getListUserEffectiveP" +
                        "ermissions()\r\n            .done(function (data) {\r\n                parseBasePerm" +
                        "issions(data);\r\n            });\r\n    }\r\n\r\n</script>\r\n\r\n\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
