//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebParts.WebParts.CreateEmployee {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class CreateEmployee {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtBirthdate;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList rbGender;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtSalary;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList chDepartment;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtProfileURL;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtProfileURLDes;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtBriefofExp;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "16.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(CreateEmployee target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtName";
            @__ctrl.MaxLength = 100;
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtBirthdate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtBirthdate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtBirthdate";
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Date;
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlrbGender() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.rbGender = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "rbGender";
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSalary() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtSalary = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Number;
            @__ctrl.ID = "txtSalary";
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlchDepartment() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.chDepartment = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "chDepartment";
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtProfileURL() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtProfileURL = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtProfileURL";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtProfileURLDes() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtProfileURLDes = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.MultiLine;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Description");
            @__ctrl.ID = "txtProfileURLDes";
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtBriefofExp() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtBriefofExp = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.MultiLine;
            @__ctrl.ID = "txtBriefofExp";
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSave";
            @__ctrl.CssClass = "btn btn-button";
            @__ctrl.EnableViewState = false;
            @__ctrl.Text = "Create";
            @__ctrl.OnClientClick = "checkPermission(); return false;";
            @__ctrl.Click -= new System.EventHandler(this.btnSave_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void @__BuildControlTree(global::EmployeeWebParts.WebParts.CreateEmployee.CreateEmployee @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<link type=""text/css"" rel=""stylesheet"" href=""/Style%20Library/CSS/bootstrap.min.css"" />
<script src=""/Style Library/Scripts/jquery-3.5.1.min.js""></script>



<div class=""container"">

    <div class=""row"">
        <div class=""col-md-3 col-sm-3"">
            <label for=""txtName"" id=""lblName"">Name</label>
        </div>
        <div class=""col-md-6 col-sm-6"">
            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtName();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n            \r\n        </div>\r\n    </div>\r\n    <div class=\"row\">\r\n        <div" +
                        " class=\"col-md-3 col-sm-3\">\r\n            <label for=\"txtBirthdate\" id=\"lblBirthd" +
                        "ate\">Birthdate</label>\r\n        </div>\r\n        <div class=\"col-md-6 col-sm-6\">\r" +
                        "\n            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            @__ctrl2 = this.@__BuildControltxtBirthdate();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n            \r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"row\">\r\n        <d" +
                        "iv class=\"col-md-3 col-sm-3\">\r\n            <label for=\"rbGender\" id=\"lblGender\">" +
                        "Gender</label>\r\n        </div>\r\n        <div class=\"col-md-6 col-sm-6\">\r\n       " +
                        "     "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl3;
            @__ctrl3 = this.@__BuildControlrbGender();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n            \r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"row\">\r\n        <d" +
                        "iv class=\"col-md-3 col-sm-3\">\r\n            <label for=\"txtSalary\" id=\"lblSalary\"" +
                        ">Salary</label>\r\n        </div>\r\n        <div class=\"col-md-6 col-sm-6\">\r\n      " +
                        "      "));
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControltxtSalary();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

            
        </div>
    </div>

    <div class=""row"">
        <div class=""col-md-3 col-sm-3"">
            <label for=""chDepartment"" id=""lblDepartment"">Department</label>
        </div>
        <div class=""col-md-6 col-sm-6"">
            "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl5;
            @__ctrl5 = this.@__BuildControlchDepartment();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

            
        </div>
    </div>

    <div class=""row"">
        <div class=""col-md-3 col-sm-3"">
            <label for=""txtProfileURL "" id=""lblProfileURL"">Profile URL</label>
        </div>
        <div class=""col-md-4 col-sm-4"">
            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControltxtProfileURL();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n        <div class=\"col-md-3 col-sm-3\">\r\n            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl7;
            @__ctrl7 = this.@__BuildControltxtProfileURLDes();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
        </div>
    </div>

    <div class=""row"">
        <div class=""col-md-3 col-sm-3"">
            <label for=""txtBriefofExp "" id=""lbltxtBriefofExp"">Brief of experience</label>
        </div>
        <div class=""col-md-6 col-sm-6"">
            "));
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            @__ctrl8 = this.@__BuildControltxtBriefofExp();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            \r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"row\">\r\n\r\n        <d" +
                        "iv class=\"col-md-6 col-sm-6\" style=\"align-content: center\">\r\n            "));
            global::System.Web.UI.WebControls.Button @__ctrl9;
            @__ctrl9 = this.@__BuildControlbtnSave();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n    </div>\r\n    \r\n    <label id=\"lblErrorMessage\"></label>\r\n   " +
                        " \r\n</div>\r\n\r\n\r\n<script type=\"text/javascript\">  \r\n    \'use strict\';\r\n    $(docum" +
                        "ent).ready(function () {\r\n      \r\n        $.ajax({\r\n            url: _spPageCont" +
                        "extInfo.webAbsoluteUrl + \"/_api/web/lists/GetByTitle(\'Employees\')/fields?$filter" +
                        "=EntityPropertyName eq \'EmployeeDepartment\'\",\r\n            type: \"GET\",\r\n       " +
                        "     headers: {\r\n                \"accept\": \"application/json;odata=verbose\",\r\n  " +
                        "          },\r\n            success: function (data) {\r\n                console.lo" +
                        "g(data.d.results[0].Choices.results);\r\n                var depChoices = data.d.r" +
                        "esults[0].Choices.results;\r\n                for (var dep of depChoices) {\r\n     " +
                        "               console.log(dep);\r\n                    $(\"select[id*=\'chDepartmen" +
                        "t\']\").append(`<option Value=\"${dep}\">${dep}</option>`);\r\n                }\r\n    " +
                        "        },\r\n            error: function (error) {\r\n                alert(JSON.st" +
                        "ringify(error));\r\n            }\r\n        });\r\n\r\n        $.ajax({\r\n            ur" +
                        "l: _spPageContextInfo.webAbsoluteUrl + \"/_api/web/lists/GetByTitle(\'Employees\')/" +
                        "fields?$filter=EntityPropertyName eq \'EmployeeGender\'\",\r\n            type: \"GET\"" +
                        ",\r\n            headers: {\r\n                \"accept\": \"application/json;odata=ver" +
                        "bose\",\r\n            },\r\n            success: function (data) {\r\n                " +
                        "console.log(data.d.results[0].Choices.results);\r\n                var genderChoic" +
                        "es = data.d.results[0].Choices.results;\r\n                for (var gender of gend" +
                        "erChoices) {\r\n                    console.log(gender);\r\n                    $(\"s" +
                        "elect[id*=\'rbGender\']\").append(`<option Value=\"${gender}\">${gender}</option>`);\r" +
                        "\n                }\r\n            },\r\n            error: function (error) {\r\n     " +
                        "           alert(JSON.stringify(error));\r\n            }\r\n        });\r\n        \r\n" +
                        "\r\n    });\r\n\r\n\r\n    var allowAdd = false;\r\n    var listTitle = \"Employees\";\r\n\r\n  " +
                        "  function CreateListItem() {\r\n        // validate Input\r\n        var valid = tr" +
                        "ue;\r\n        var txtError = $(\"#lblErrorMessage\");\r\n        txtError.val(\"\");\r\n " +
                        "       var textName = $(\"input[id*=\'txtName\']\").val();\r\n        var birthDate = " +
                        "$(\"input[id *= \'txtBirthdate\']\").val();\r\n        var txtSalary = $(\"input[id *= " +
                        "\'txtSalary\']\").val();\r\n        var txtBriefofExp = $(\"textarea[id *= \'txtBriefof" +
                        "Exp\']\").val();\r\n        var emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-" +
                        "zA-Z]{2,4}$/;\r\n\r\n        if (textName.length < 20 || textName.length > 100) {\r\n " +
                        "           txtError.append(\"Name Length between 20 & 100 \").show();\r\n           " +
                        " valid = false;\r\n        }\r\n        if (new Date(birthDate) > new Date() || birt" +
                        "hDate === \"\") {\r\n            txtError.append(\" Date is inValid\");\r\n            v" +
                        "alid = false;\r\n        }\r\n        if (txtSalary === null || txtSalary === undefi" +
                        "ned) {\r\n            txtError.append(\" Salary required\");\r\n            valid = fa" +
                        "lse;\r\n        }\r\n        if (txtBriefofExp === null || txtBriefofExp === undefin" +
                        "ed || txtBriefofExp.length > 200) {\r\n            txtError.append(\" Brief  requir" +
                        "ed\");\r\n            valid = false;\r\n        }\r\n        if (!valid) {\r\n           " +
                        " txtError.show();\r\n        }\r\n\r\n        var siteURL = _spPageContextInfo.webAbso" +
                        "luteUrl;\r\n        console.log(\"from top nav - \" + siteURL);\r\n        var apiPath" +
                        " = siteURL + \"/_api/lists/getbytitle(\'Employee\')/items\";\r\n\r\n\r\n        if (valid)" +
                        " {\r\n            var item = {\r\n                \"__metadata\": {\r\n                 " +
                        "   \"type\": \"SP.Data.EmployeeListItem\"\r\n                },\r\n                \"Titl" +
                        "e\": $(\"input[id*=\'txtName\']\").val(),\r\n                \"EmployeeName\": $(\"input[i" +
                        "d *= \'txtName\']\").val(),\r\n                \"EmployeeBirthdate\": $(\"input[id *= \'t" +
                        "xtBirthdate\']\").val(),\r\n                \"BriefOfExperience\": $(\"textarea[id *= \'" +
                        "txtBriefofExp\']\").val(),\r\n                \"EmployeeGender\": $(\"select[id*=\'rbGen" +
                        "der\'] :selected\").val(),\r\n                \"EmployeeSalary\": parseInt($(\"input[id" +
                        " *= \'txtSalary\']\").val()),\r\n                \"EmployeeDepartment\": $(\"select[id*=" +
                        "\'chDepartment\'] :selected\").val(),\r\n                \"ProfileURL\": {\r\n           " +
                        "         \'__metadata\': { \'type\': \'SP.FieldUrlValue\' },\r\n                    \'Des" +
                        "cription\': $(\"textarea[id *= \'txtProfileURLDes\']\").val(),\r\n                    \'" +
                        "Url\': $(\"input[id *= \'txtProfileURL\']\").val()\r\n                }\r\n            };" +
                        "\r\n            siteURL = _spPageContextInfo.webAbsoluteUrl;\r\n            console." +
                        "log(\"from top nav - \" + siteURL);\r\n            var apiPath = siteURL + \"/_api/li" +
                        "sts/getbytitle(\'Employees\')/items\";\r\n            $.ajax({\r\n                url: " +
                        "apiPath,\r\n                type: \"POST\",\r\n                headers: {\r\n           " +
                        "         \"accept\": \"application/json;odata=verbose\",\r\n                    \"X-Req" +
                        "uestDigest\": $(\"#__REQUESTDIGEST\").val(),\r\n                    \"content-Type\": \"" +
                        "application/json;odata=verbose\"\r\n                },\r\n                data: JSON." +
                        "stringify(item),\r\n                //\"{__metadata:{\'type\':\'SP.Data.EmployeesListI" +
                        "tem\'},EmployeeName: \" + $(\"input[id*=\'txtName\']\").val() + \",Title: \" + $(\"input[" +
                        "id*=\'txtName\']\").val() + \",EmployeeBirthdate: \" + $(\"input[id*=\'txtBirthdate\']\")" +
                        ".val() + \",BriefOfExperience:\" + $(\"input[id*=\'txtBriefofExp\']\").val() + \",Gende" +
                        "r:Male,Salary: \" + $(\"input[id*=\'txtSalary\']\").val() + \",EmployeeDepartment:HR,P" +
                        "rofileURL:http://nsasa  } \",\r\n                async: false,\r\n                suc" +
                        "cess: function (data) {\r\n                    console.log(data.d.results);\r\n     " +
                        "               var r = confirm(\"Successful Message!\");\r\n                    if (" +
                        "r == true) {\r\n                        window.location.reload();\r\n               " +
                        "     }\r\n                }, eror: function (data) {\r\n                    console." +
                        "log(\"An error occurred. Please try again.\");\r\n                }\r\n            });" +
                        "\r\n        }\r\n\r\n    }\r\n\r\n\r\n\r\n    // check permoissions forUser\r\n    function getL" +
                        "istUserEffectivePermissions() {\r\n        var endpointUrl = _spPageContextInfo.we" +
                        "bAbsoluteUrl + \"/_api/web/lists/getbytitle(\'\" + listTitle + \"\')/getusereffective" +
                        "permissions(@u)?@u=\'\" + encodeURIComponent(_spPageContextInfo.userLoginName) + \"" +
                        "\'\";\r\n        return $.getJSON(endpointUrl);\r\n    }\r\n\r\n    function parseBasePerm" +
                        "issions(value) {\r\n        var permissions = new SP.BasePermissions();\r\n        p" +
                        "ermissions.initPropertiesFromJson(value);\r\n        allowAdd = permissions.has(SP" +
                        ".PermissionKind.addListItems);\r\n        if (allowAdd)\r\n            CreateListIte" +
                        "m();\r\n        console.log(allowAdd);\r\n    }\r\n\r\n\r\n    function checkPermission() " +
                        "{\r\n        debugger;\r\n        getListUserEffectivePermissions()\r\n            .do" +
                        "ne(function (data) {\r\n                parseBasePermissions(data);\r\n            }" +
                        ");\r\n    }\r\n</script>\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
